Repository quipucords/quipucords-ui, pull requests merged in 2022-10, with the labels that each got.

#179 refactor(locale): component strings
  public/locales/en.json
  src/components/addSourceWizard/__tests__/__snapshots__/addSourceWizardStepTwo.test.js.snap
  src/components/addSourceWizard/addSourceWizardStepTwo.js
  src/components/createScanDialog/__tests__/__snapshots__/createScanDialog.test.js.snap
  src/components/createScanDialog/createScanDialog.js
  src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap
  src/components/mergeReportsDialog/__tests__/__snapshots__/mergeReportsDialog.test.js.snap
  src/components/mergeReportsDialog/mergeReportsDialog.js
  src/components/touchspin/__tests__/__snapshots__/touchspin.test.js.snap
  src/components/touchspin/__tests__/touchspin.test.js
  src/components/touchspin/touchspin.js
Labels: pf4

#183 fix(credentialsTableCells): discovery-197 auth type string
  src/components/credentials/__tests__/__snapshots__/credentials.test.js.snap
  src/components/credentials/__tests__/__snapshots__/credentialsTableCells.test.js.snap
  src/components/credentials/credentialsTableCells.js
  src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap
  src/constants/__tests__/__snapshots__/apiConstants.test.js.snap
  src/constants/apiConstants.js
Labels: bug, pf4

#182 fix(server): discovery-198 replace assets paths
  templates/registration/logged_out.html
  templates/registration/login.html
  tests/__snapshots__/templates.test.js.snap
Labels: bug, build
