Repository quipucords/quipucords-ui, pull requests merged in 2022-09, with the labels that each got.

#153 feat(radio): add PF4 radio to forms
  src/components/addSourceWizard/__tests__/__snapshots__/addSourceWizardStepOne.test.js.snap
  src/components/addSourceWizard/addSourceWizardStepOne.js
  src/components/form/__tests__/__snapshots__/radio.test.js.snap
  src/components/form/__tests__/radio.test.js
  src/components/form/radio.js
  src/styles/app/_patternflyOverrides.scss
  tests/__snapshots__/dist.test.js.snap
Labels: pf4, pf4: forms

#155 refactor(checkbox): refactor forms checkbox to use PF4 components
  src/components/addSourceWizard/__tests__/__snapshots__/addSourceWizardStepTwo.test.js.snap
  src/components/addSourceWizard/addSourceWizardStepTwo.js
  src/components/createScanDialog/__tests__/__snapshots__/createScanDialog.test.js.snap
  src/components/createScanDialog/createScanDialog.js
  src/components/form/__tests__/__snapshots__/checkbox.test.js.snap
  src/components/form/__tests__/checkbox.test.js
  src/components/form/checkbox.js
  src/styles/app/_patternflyOverrides.scss
Labels: pf4, pf4: forms

#164 refactor(router): react router, npm update
  package.json
  src/components/app.js
  src/components/credentials/__tests__/__snapshots__/credentials.test.js.snap
  src/components/credentials/credentials.js
  src/components/pageLayout/__tests__/__snapshots__/pageLayout.test.js.snap
  src/components/pageLayout/__tests__/pageLayout.test.js
  src/components/pageLayout/pageLayout.js
  src/components/router/__tests__/__snapshots__/router.test.js.snap
  src/components/router/__tests__/__snapshots__/routerConstants.test.js.snap
  src/components/router/router.js
  src/components/router/routerConstants.js
  src/components/scans/__tests__/__snapshots__/scans.test.js.snap
  src/components/scans/__tests__/__snapshots__/scansEmptyState.test.js.snap
  src/components/scans/__tests__/scansEmptyState.test.js
  src/components/scans/scans.js
  src/components/sources/__tests__/__snapshots__/sources.test.js.snap
  src/components/sources/sources.js
  src/redux/index.js
  yarn.lock
Labels: tech debt

#165 refactor(button,icon,spinner): discovery-149 pf4 replacements
  src/components/contextIcon/__tests__/__snapshots__/contextIcon.test.js.snap
  src/components/contextIcon/contextIcon.js
  src/components/createScanDialog/__tests__/__snapshots__/createScanDialog.test.js.snap
  src/components/createScanDialog/__tests__/createScanDialog.test.js
  src/components/createScanDialog/createScanDialog.js
  src/components/mergeReportsDialog/__tests__/__snapshots__/mergeReportsDialog.test.js.snap
  src/components/mergeReportsDialog/mergeReportsDialog.js
  src/components/pageLayout/__tests__/__snapshots__/pageLayout.test.js.snap
  src/components/pageLayout/pageLayout.js
  src/components/scans/__tests__/__snapshots__/scanDownload.test.js.snap
  src/components/scans/__tests__/__snapshots__/scanJobsList.test.js.snap
  src/components/scans/scanDownload.js
  src/components/scans/scanJobsList.js
  src/components/tooltip/tooltip.js
Labels: pf4, pf4:clean up

#166 fix(sources): discovery-154, activate scans button
  src/components/sources/sources.js
Labels: pf4, pf4:clean up

#170 fix(build): discovery-174 css font paths
  package.json
  scripts/templateCssPaths.js
Labels: bug, pf4

#173 feat(viewContext): discovery-151 context for views
  src/components/credentials/__tests__/__snapshots__/credentials.test.js.snap
  src/components/credentials/__tests__/__snapshots__/credentialsContext.test.js.snap
  src/components/credentials/__tests__/credentials.test.js
  src/components/credentials/credentials.js
  src/components/credentials/credentialsContext.js
  src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap
  src/components/pageLayout/__tests__/__snapshots__/pageLayout.test.js.snap
  src/components/router/__tests__/__snapshots__/router.test.js.snap
  src/components/router/__tests__/__snapshots__/routerConstants.test.js.snap
  src/components/router/routerConstants.js
  src/components/scans/__tests__/__snapshots__/scans.test.js.snap
  src/components/scans/__tests__/__snapshots__/scansContext.test.js.snap
  src/components/scans/__tests__/scans.test.js
  src/components/scans/__tests__/scansEmptyState.test.js
  src/components/scans/scans.js
  src/components/scans/scansContext.js
  src/components/scans/scansEmptyState.js
  src/components/sources/__tests__/__snapshots__/sources.test.js.snap
  src/components/sources/__tests__/__snapshots__/sourcesContext.test.js.snap
  src/components/sources/__tests__/sources.test.js
  src/components/sources/sources.js
  src/components/sources/sourcesContext.js
  src/components/view/viewContext.js
  src/constants/__tests__/__snapshots__/apiConstants.test.js.snap
  src/constants/apiConstants.js
  src/redux/reducers/viewOptionsReducer.js
Labels: pf4

#162 cleanup(sources): localize labels for dialogs in sources view
  public/locales/en.json
  src/components/addSourceWizard/__tests__/__snapshots__/addSourceWizardStepOne.test.js.snap
  src/components/addSourceWizard/__tests__/__snapshots__/addSourceWizardStepTwo.test.js.snap
  src/components/addSourceWizard/addSourceWizardStepOne.js
  src/components/addSourceWizard/addSourceWizardStepTwo.js
  src/components/createScanDialog/__tests__/__snapshots__/createScanDialog.test.js.snap
  src/components/createScanDialog/createScanDialog.js
  src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap
Labels: pf4
