Repository quipucords/quipucords-ui, pull requests merged in 2022-08, with the labels that each got.

#129 Refactor(Pagination): convert Pagination instances to PF4
  src/components/scans/__tests__/__snapshots__/scans.test.js.snap
  src/components/sources/__tests__/__snapshots__/sources.test.js.snap
  src/components/viewPaginationRow/__tests__/__snapshots__/viewPaginationRow.test.js.snap
  src/components/viewPaginationRow/viewPaginationRow.js
  src/redux/constants/__tests__/__snapshots__/index.test.js.snap
  src/redux/constants/viewPaginationConstants.js
  src/redux/reducers/__tests__/__snapshots__/viewOptionsReducer.test.js.snap
  src/redux/reducers/__tests__/viewOptionsReducer.test.js
  src/redux/reducers/viewOptionsReducer.js
  src/styles/app/_views.scss
  tests/__snapshots__/dist.test.js.snap
Labels: pf4

#137 chore(deps): quipudocs bump
  package.json
  yarn.lock
Labels: build

#136 refactor(buttons): convert buttons on Sources screen to PF4
  src/components/sources/__tests__/__snapshots__/sourceListItem.test.js.snap
  src/components/sources/__tests__/__snapshots__/sources.test.js.snap
  src/components/sources/sourceListItem.js
  src/components/sources/sources.js
  src/styles/app/_views.scss
Labels: pf4

#140 fix(table): discovery-154 key generation
  src/components/table/__tests__/__snapshots__/table.test.js.snap
  src/components/table/__tests__/__snapshots__/tableHelpers.test.js.snap
  src/components/table/__tests__/tableHelpers.test.js
  src/components/table/table.js
  src/components/table/tableHelpers.js
Labels: pf4, pf4:wrapper-component

#143 fix(build): discovery-174 templates css
  package.json
  scripts/post.sh
  scripts/pre.sh
  tests/__snapshots__/dist.test.js.snap
Labels: bug, pf4

#142 refactor(buttons): convert buttons in scans and credentials list views
  src/components/credentials/__tests__/__snapshots__/credentialsListItem.test.js.snap
  src/components/credentials/credentialListItem.js
  src/components/scans/__tests__/__snapshots__/scanListItem.test.js.snap
  src/components/scans/__tests__/__snapshots__/scans.test.js.snap
  src/components/scans/scanListItem.js
  src/components/scans/scans.js
Labels: pf4

#144 refactor(Alert): convert alert in Create Scan Dialog to PF4
  src/components/createScanDialog/__tests__/__snapshots__/createScanDialog.test.js.snap
  src/components/createScanDialog/__tests__/createScanDialog.test.js
  src/components/createScanDialog/createScanDialog.js
Labels: pf4

#141 refactor(sources): discovery-154, pf4 table
  public/locales/en.json
  src/components/addSourceWizard/__tests__/__snapshots__/addSourceWizardContext.test.js.snap
  src/components/addSourceWizard/__tests__/addSourceWizardContext.test.js
  src/components/addSourceWizard/addSourceWizardContext.js
  src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap
  src/components/pageLayout/__tests__/__snapshots__/pageLayout.test.js.snap
  src/components/router/__tests__/__snapshots__/router.test.js.snap
  src/components/router/__tests__/__snapshots__/routerConstants.test.js.snap
  src/components/router/routerConstants.js
  src/components/scanHostList/scanHostList.js
  src/components/scans/__tests__/__snapshots__/scans.test.js.snap
  src/components/scans/__tests__/__snapshots__/scansEmptyState.test.js.snap
  src/components/scans/scans.js
  src/components/scans/scansEmptyState.js
  src/components/sources/__tests__/__snapshots__/sourceCredentialsList.test.js.snap
  src/components/sources/__tests__/__snapshots__/sourceListItem.test.js.snap
  src/components/sources/__tests__/__snapshots__/sources.test.js.snap
  src/components/sources/__tests__/__snapshots__/sourcesContext.test.js.snap
  src/components/sources/__tests__/__snapshots__/sourcesEmptyState.test.js.snap
  src/components/sources/__tests__/__snapshots__/sourcesTableCells.test.js.snap
  src/components/sources/__tests__/sourceCredentialsList.test.js
  src/components/sources/__tests__/sourceListItem.test.js
  src/components/sources/__tests__/sources.test.js
  src/components/sources/__tests__/sourcesContext.test.js
  src/components/sources/__tests__/sourcesTableCells.test.js
  src/components/sources/sourceCredentialsList.js
  src/components/sources/sourceListItem.js
  src/components/sources/sources.js
  src/components/sources/sourcesContext.js
  src/components/sources/sourcesEmptyState.js
  src/components/sources/sourcesTableCells.js
  src/redux/common/reduxHelpers.js
  src/redux/constants/__tests__/__snapshots__/index.test.js.snap
  src/redux/constants/index.js
  src/redux/constants/sourcesConstants.js
  src/redux/reducers/__tests__/__snapshots__/sourcesReducer.test.js.snap
  src/redux/reducers/__tests__/sourcesReducer.test.js
  src/redux/reducers/sourcesReducer.js
  src/redux/selectors/scansSelectors.js
  tests/__snapshots__/code.test.js.snap
  tests/__snapshots__/dist.test.js.snap
Labels: pf4
