Repository quipucords/quipucords-ui, pull requests merged in 2024-05, with the labels that each got.

#346 2 of 4, WIP ci: ds-661 dependabot groups for bulk updates
  .github/dependabot.yml
  CONTRIBUTING.md
  package.json
  scripts/dependencies.sh
  yarn.lock
Labels: build

#362 build(deps): ds-661 move to i18next-http-backend
  package.json
  src/components/i18n/i18n.js
  yarn.lock
Labels: build

#365 fix(scans): ds-98 disable expandable sources
  src/components/scans/__tests__/__snapshots__/scans.test.js.snap
  src/components/scans/__tests__/__snapshots__/scansTableCells.test.js.snap
  src/components/scans/scanSourceList.js
  src/components/scans/scans.js
  src/components/scans/scansTableCells.js
Labels: bug

#367 fix(credentials): ds-205 disable edit for encrypted fields
  src/components/createCredentialDialog/createCredentialDialog.js
  src/services/credentialsService.js
Labels: bug

#366 chore: drop support for brms
  config/cspell.config.json
  public/locales/en.json
  src/components/createScanDialog/createScanDialog.js
  src/components/i18n/__tests__/__snapshots__/i18n.test.js.snap
  src/constants/__tests__/__snapshots__/apiConstants.test.js.snap
  src/constants/apiConstants.js
Labels: hold

#371 ci: ds-652 dependabot groups for bulk updates
  .github/dependabot.yml
  CONTRIBUTING.md
Labels: build
